spring:
  profiles:
    #运行的环境
    active: prod
  application:
    name: yanchat
  datasource:
    url: jdbc:mysql://${yanchat.mysql.ip}:${yanchat.mysql.port}/${yanchat.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${yanchat.mysql.username}
    password: ${yanchat.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis服务器地址
    host: ${yanchat.redis.host}
    # Redis服务器端口号
    port: ${yanchat.redis.port}
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: ${yanchat.redis.password}
  jackson:
    serialization:
      write-dates-as-timestamps: true